# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
    forge_modules:
        sudo:
            repo: "saz/sudo"
            ref: "6.0.0"
        apt:
            repo: "puppetlabs/apt"
            ref: "4.5.1"
        zypprepo:
            repo: "puppet/zypprepo"
            ref: "2.2.2"
        stdlib:
            repo: "puppetlabs/stdlib"
            ref: "4.25.1"
        yumrepo_core:
            repo: "puppetlabs/yumrepo_core"
            ref: "1.0.6"
        logrotate:
            repo: "puppet/logrotate"
            ref: "5.0.0"
