---
driver:
  name: "docker"
  test_base_path: "test"
  use_sudo: false # because of https://github.com/test-kitchen/kitchen-docker/issues/207
  memory: "2G"
  provision_command: |
    touch /etc/sudoers.d/10_testsudo3 && chmod 0440 /etc/sudoers.d/10_testsudo3 && chmod 0440 /etc/sudoers.d/kitchen

provisioner:
  name: "puppet_apply"
  manifest: "site.pp"
  puppet_debug: true
  ignored_paths_from_root:
    - "spec"
    - "vendor"
  ignore_spec_fixtures: true

platforms:
  - name: "ubuntu-22.04"
    provisioner:
      name: "puppet_apply"
      puppet_apt_collections_repo: "http://apt.puppet.com/puppet7-release-jammy.deb"
  - name: "ubuntu-20.04"
    provisioner:
      name: "puppet_apply"
      puppet_apt_collections_repo: "http://apt.puppet.com/puppet7-release-focal.deb"

verifier:
  name: serverspec

suites:
  - name: "default"
    verifier:
      custom_install_command: sudo ln -s /usr/bin/bundle3.0 /usr/local/bin/bundle
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'
  - name: "monitors"
    verifier:
      custom_install_command: sudo ln -s /usr/bin/bundle3.0 /usr/local/bin/bundle
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'
  - name: "crondate"
    verifier:
      custom_install_command: sudo ln -s /usr/bin/bundle3.0 /usr/local/bin/bundle
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'
