.gitignore:
    paths:
        - "/test/integration/**/.librarian"
        - "/test/integration/**/.tmp"
        - ".kitchen"
        - ".vscode"
Gemfile:
    required:
        ":development":
            - gem: "kitchen-docker"
              version: "2.9.0"
            - gem: "kitchen-puppet"
              version: "3.5.1"
            - gem: "serverspec"
              version: "2.41.5"
            - gem: "test-kitchen"
              version: "2.2.5"
    optional:
        ':development':
            - gem: 'github_changelog_generator'
              git: 'https://github.com/skywinder/github-changelog-generator'
              ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
              condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
Rakefile:
    requires:
        - "kitchen/rake_tasks"
    extras:
        - "Kitchen::RakeTasks.new"
        - |
            task :integration_test do
              [:metadata_lint, :lint, :validate, :spec].each do |test|
                Rake::Task[test].invoke
              end
              Rake::Task['kitchen:all'].invoke
            end
.travis.yml:
    includes:
        - env: PUPPET_GEM_VERSION="~> 6.0" CHECK=integration_test
          rvm: 2.5.3
          stage: spec
          script: 'travis_wait 40 bundle exec rake $CHECK'
    user: "dodevops"
    secure: "oS4IaXgf7Vvx4dGRGm8YNUVSaiSh90+nakdVFAX7oR6+Imvt5JGEYPoPpVgXlFwmHjN1ewqKqtqB3giW8gKUVJFyp/vG8piE8eaKQ4gmK7P+iMW/MVvifXt0NH+MeeRK7OCkL1KN4Z7D4pFZyqKEWUuTeIDOLwm44N9AJvFyWU8rRCMARlDE/ALSj+8e1oK9w6+T2/wW+x+WfI4xA+d+MG84VJpBS8qx6GACKDJ5X8+dPIPvOITeitn+GLpfO+z0Z+5Am6EJf5UJiaFnWPaJguan8+RkeAQBulvfRLv6nCcCQ3jTb+0fCp6Tdc2Gxjf6uBilj2+GO7KUJ5tsKIiUxvO/MQNuPEAP4MdK7CR4YL+RS3vZrrNLOHmG83RM5Yp8NA1aEI/bIzWDbh6tWE2SP7BFylLA8z1EV1wkgidi1awJ47rb5XduF9Sg4xBteEcpaOrCJp6mQVCinMhf4h6+lrJap0M9txYfWT3nwrmq70x3B6/GHhmOLQQzwjv47IezgNz0hpCeGAfDspchmw0ufw+SFceXxOR/chO1GpZnNW7bs1hJsti6dvR1fKSXC9EgxlJQC4PzDPJumFDVc2ZI41/1EjMFD51mK8aURYZUG788DjdsmUA0qCIluh6cKg8sgX8vkO546gCnINWoxBh9eVgrUXrYmvazmMDdAp1ctqs="
